version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-free:latest
    container_name: oracle-supermarket
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=SecretPassword123
      - APP_USER=sieuthi_user
      - APP_USER_PASSWORD=SecretPassword123
      - ORACLE_DATABASE=FREEPDB1
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data: