# K?t n?i t?i MariaDB trong Docker (C?ng 3307)
spring.datasource.url=jdbc:mariadb://localhost:3307/sieuthi_db
spring.datasource.username=root
spring.datasource.password=123456

# Hi?n th? câu l?nh SQL ra màn hình console ?? b?n ki?m tra
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update